name: Tag
on:
  push:
    branch:
      - "main"
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Unshallow
        run: git fetch --tags --prune --unshallow
      - name: install autotag binary
        run: |
          curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      - name: increment version
        run: |
          autotag --branch main